config/routes.rb
Rails.application.routes.draw do

  resources :projects
  resources :users, :only => [:new, :create]

end

app/models/funding.rb
class Funding < ActiveRecord::Base
  # belongs_to :project
  belongs_to :reward
  belongs_to :backer, class_name: "User"
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :fundings, through: :rewards
  has_many :rewards
  belongs_to :hacker, class_name: "User"
  has_many :backers, through: :fundings, source: :backer
end

app/models/reward.rb
class Reward < ActiveRecord::Base
  belongs_to :project
  has_many :fundings
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  has_many :projects, :foreign_key => "hacker_id"
  has_many :fundings, :foreign_key => "backer_id"

  validates :password, length: { minimum: 3 }
  validates :password, confirmation: true
  validates :password_confirmation, presence: true

  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
  end

  def create
    @project = projects_url.new(params[:id])

    if @project.save
      redirect_to projects_url
     else
      render :new
     end
  end

  def show
    @project = Project.find(params[:id])
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])

    if @project.update_attributes(project_params)
      redirect_to project_path(@project)
    else
      render :edit
    end
  end

  private
  def project_params
    params.require(:project).permit(:title, :description, :start_date, :end_date, :target)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to projects_url, :notice => "Sign up succeeded!"
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crowdfunder</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/projects/edit.html.erb
<h1>Projects#edit</h1>
<p>Find me in app/views/projects/edit.html.erb</p>

app/views/projects/index.html.erb
<div>
  <h1>Crowdfunder</h1>
  <%= link_to "Add a New Project", new_project_path %><br />
</div>


<div id="projects">
  <%= render @projects %>
</div>

app/views/projects/new.html.erb
<h1>Projects#new</h1>
<p>Find me in app/views/projects/new.html.erb</p>

app/views/projects/show.html.erb
<h1>Projects#show</h1>
<p>Find me in app/views/projects/show.html.erb</p>

app/views/users/_form.html.erb
<div class="field">
   <%= f.label :email %><br />
   <%= f.string :email %>
</div>

<div class="field">
   <%= f.label :password %><br />
   <%= f.password_field :password %>
</div>
<div class="field">
   <%= f.label :password_confirmation %><br />
   <%= f.password_field :password_confirmation %>
</div>

<div>
    <%= f.submit "Submit" %>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Login or Create a New Account</h1>

<%= render 'form' %>